//APP LANGUAGE CONFIG
export const LANGUAGE_CHANGE_LOCALE = 'LANGUAGE/CHANGE_LOCALE'
export const LANGUAGE_TOGGLE_LOCALE = 'LANGUAGE/TOOGLE_LOCALE'
export const NETWORK_CHANGE_STATE = 'NETWORK/CHANGE_STATE'
//FOR AUTH ACTION
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_FAILED = 'AUTH/LOGIN_FAILED'
export const LOG_OUT = 'AUTH/LOGOUT'
export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST'
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS'
export const REGISTER_FAILED = 'AUTH/REGISTER_FAILED'
export const REGISTER_REQUEST = 'AUTH/REGISTER_REQUEST'
export const RESET_ERROR = 'AUTH/RESET_ERROR'
export const VERIFY = 'AUTH/VERIFY'

// export const LOGIN_PHONE_REQUEST = 'AUT/LOGIN_PHONE_REQUEST'
// export const VERIFY_PHONE_SUCCESS = 'AUT/VERIFY_PHONE_SUCCESS'
// export const VERIFY_PHONE_FAIL = 'AUT/VERIFY_PHONE_FAIL'
// export const VERIFY_PHONE_REQUEST = 'AUT/VERIFY_PHONE_REQUEST'